"""Markdown report generation."""

from __future__ import annotations

from .config import DEFAULT_PRODUCTION_PATTERNS
from .models import ComparisonSummary, Finding, ScanResult
from .prioritise import PrioritisedFinding, prioritise_findings
from .redaction import redact_secrets, truncate


def generate_report(
    scan: ScanResult,
    comparison: ComparisonSummary,
    *,
    top_items: list[PrioritisedFinding] | None = None,
    production_patterns: tuple[str, ...] = DEFAULT_PRODUCTION_PATTERNS,
    top_limit: int = 3,
) -> str:
    """Generate a concise Markdown report for Slack and artifacts."""

    top = top_items or prioritise_findings(
        scan.findings,
        limit=top_limit,
        production_patterns=production_patterns,
    )
    active_count = int(scan.summary.get("active_findings", len(scan.findings)))
    lines = [
        "# DriftBeacon Report",
        "",
        "## At a glance",
        f"**Repository:** {redact_secrets(scan.repository)}  ",
        f"**Branch:** {redact_secrets(scan.branch)}  ",
        f"**Commit:** `{scan.commit_sha[:12]}`  ",
        f"**Health score:** {scan.health_score}/100 ({_health_trend(comparison)})  ",
        f"**Active findings:** {active_count}  ",
        f"**Trend:** {_change_sentence(comparison)}",
        "",
        "## What happened",
        _what_happened(scan, comparison, active_count),
        "",
        "## What changed",
    ]
    lines.extend(_change_lines(comparison))
    lines.extend(["", "## Fix these first"])
    if top:
        for index, item in enumerate(top, start=1):
            lines.extend(_finding_lines(index, item))
    else:
        lines.append("No active findings were detected.")

    lines.extend(["", "## Scanner status"])
    for status in scan.scanner_statuses.values():
        pretty_state = status.status.capitalize()
        message = redact_secrets(status.message)
        suffix = f": {message}" if message else ""
        lines.append(f"- {status.name.capitalize()}: {pretty_state}{suffix}")

    if comparison.resolved_findings:
        lines.extend(["", "## Recently resolved"])
        for finding in comparison.resolved_findings[:5]:
            location = _location(finding)
            lines.append(
                f"- {_severity_label(finding)}: {redact_secrets(finding.title)} ({location})"
            )

    lines.extend(["", "_Generated by DriftBeacon._", ""])
    return "\n".join(lines)


def generate_job_summary(report_markdown: str, max_chars: int = 6000) -> str:
    """Create a GitHub Actions summary sized for quick review."""

    if len(report_markdown) <= max_chars:
        return report_markdown
    return (
        report_markdown[: max_chars - 80].rstrip()
        + "\n\n_Report truncated. Full report is attached as an artifact._\n"
    )


def _finding_lines(index: int, item: PrioritisedFinding) -> list[str]:
    finding = item.finding
    return [
        f"### {index}. {redact_secrets(finding.title)}",
        f"**Severity:** {_severity_label(finding)} | **Category:** {finding.category}  ",
        f"**Location:** {_location(finding)}  ",
        f"**Why:** {redact_secrets(item.reason)}  ",
        f"**Action:** {_recommended_action(finding)}",
        "",
    ]


def _recommended_action(finding: Finding) -> str:
    if finding.remediation:
        return redact_secrets(truncate(finding.remediation, 240))
    if finding.documentation_url:
        return f"Review {finding.documentation_url} and update the affected resource."
    return "Review the affected resource and apply the scanner recommendation."


def _location(finding: Finding) -> str:
    if finding.file_path and finding.line_start:
        return f"{redact_secrets(finding.file_path)}:{finding.line_start}"
    if finding.file_path:
        return redact_secrets(finding.file_path)
    if finding.resource:
        return redact_secrets(finding.resource)
    return "Unknown"


def _severity_label(finding: Finding) -> str:
    if finding.severity == "unknown":
        return "Unspecified"
    return finding.severity.capitalize()


def _health_trend(comparison: ComparisonSummary) -> str:
    if comparison.health_score_change is None:
        return "first scan"
    if comparison.health_score_change > 0:
        return f"up {_plural(comparison.health_score_change, 'point')}"
    if comparison.health_score_change < 0:
        return f"down {_plural(abs(comparison.health_score_change), 'point')}"
    return "unchanged"


def _what_happened(
    scan: ScanResult, comparison: ComparisonSummary, active_count: int
) -> str:
    scanner_summary = _scanner_summary(scan)
    if active_count == 0:
        finding_summary = "No active findings were detected."
    else:
        finding_summary = f"DriftBeacon normalized {_plural(active_count, 'active finding')}."
    if comparison.has_baseline:
        return f"{scanner_summary} {finding_summary} Health is {scan.health_score}/100."
    return (
        f"{scanner_summary} {finding_summary} This is the first baseline, so current findings "
        "are treated as new."
    )


def _scanner_summary(scan: ScanResult) -> str:
    if not scan.scanner_statuses:
        return "No scanner status was recorded."
    success = sum(1 for status in scan.scanner_statuses.values() if status.status == "success")
    partial = sum(1 for status in scan.scanner_statuses.values() if status.status == "partial")
    failed = sum(1 for status in scan.scanner_statuses.values() if status.status == "failed")
    skipped = sum(1 for status in scan.scanner_statuses.values() if status.status == "skipped")
    parts: list[str] = []
    if success:
        parts.append(_plural(success, "successful scanner"))
    if partial:
        parts.append(_plural(partial, "partial scanner"))
    if failed:
        parts.append(_plural(failed, "failed scanner"))
    if skipped:
        parts.append(_plural(skipped, "skipped scanner"))
    return "Scanner status: " + ", ".join(parts) + "."


def _change_lines(comparison: ComparisonSummary) -> list[str]:
    if not comparison.has_baseline:
        return ["- First scan: no previous baseline existed."]
    return [
        f"- {_plural(len(comparison.new_findings), 'new finding')}",
        f"- {_plural(len(comparison.recurring_findings), 'recurring finding')}",
        f"- {_plural(len(comparison.resolved_findings), 'resolved finding')}",
        f"- {_plural(len(comparison.severity_changes), 'severity change')}",
        f"- Health score {_health_trend(comparison)}",
    ]


def _change_sentence(comparison: ComparisonSummary) -> str:
    if not comparison.has_baseline:
        return "first scan"
    return (
        f"{_plural(len(comparison.new_findings), 'new finding')}, "
        f"{_plural(len(comparison.recurring_findings), 'recurring finding')}, "
        f"{_plural(len(comparison.resolved_findings), 'resolved finding')}, "
        f"health score {_health_trend(comparison)}"
    )


def _plural(count: int, label: str) -> str:
    suffix = "" if count == 1 else "s"
    return f"{count} {label}{suffix}"
