"""Markdown report generation."""

from __future__ import annotations

from .config import DEFAULT_PRODUCTION_PATTERNS
from .models import ComparisonSummary, Finding, ScanResult
from .prioritise import PrioritisedFinding, prioritise_findings
from .redaction import redact_secrets, truncate


def generate_report(
    scan: ScanResult,
    comparison: ComparisonSummary,
    *,
    top_items: list[PrioritisedFinding] | None = None,
    production_patterns: tuple[str, ...] = DEFAULT_PRODUCTION_PATTERNS,
    top_limit: int = 3,
) -> str:
    """Generate a concise Markdown report for Slack and artifacts."""

    top = top_items or prioritise_findings(
        scan.findings,
        limit=top_limit,
        production_patterns=production_patterns,
    )
    lines = [
        "# DriftBeacon Weekly",
        f"**Repository:** {redact_secrets(scan.repository)}  ",
        f"**Branch:** {redact_secrets(scan.branch)}  ",
        f"**Commit:** `{scan.commit_sha[:12]}`  ",
        f"**Health score:** {scan.health_score}/100, {_health_trend(comparison)}  ",
        f"**Active findings:** {scan.summary.get('active_findings', len(scan.findings))}  ",
        f"**New:** {len(comparison.new_findings)}  ",
        f"**Resolved:** {len(comparison.resolved_findings)}",
        "",
        "## Fix these first",
    ]
    if top:
        for index, item in enumerate(top, start=1):
            lines.extend(_finding_lines(index, item))
    else:
        lines.append("No active findings were detected.")

    lines.extend(
        [
            "",
            "## Changes since the previous scan",
        ]
    )
    if comparison.has_baseline:
        lines.extend(
            [
                f"- {_plural(len(comparison.new_findings), 'new finding')}",
                f"- {_plural(len(comparison.resolved_findings), 'resolved finding')}",
                f"- {_plural(len(comparison.recurring_findings), 'recurring finding')}",
                f"- {_plural(len(comparison.severity_changes), 'severity change')}",
            ]
        )
    else:
        lines.append("- First scan: no previous baseline existed, so all current findings are new.")

    lines.extend(["", "## Scanner status"])
    for status in scan.scanner_statuses.values():
        pretty_state = status.status.capitalize()
        message = redact_secrets(status.message)
        suffix = f": {message}" if message else ""
        lines.append(f"- {status.name.capitalize()}: {pretty_state}{suffix}")

    if comparison.resolved_findings:
        lines.extend(["", "## Recently resolved"])
        for finding in comparison.resolved_findings[:5]:
            location = _location(finding)
            lines.append(
                f"- {finding.severity.capitalize()}: {redact_secrets(finding.title)} ({location})"
            )

    lines.extend(["", "_Generated by DriftBeacon._", ""])
    return "\n".join(lines)


def generate_job_summary(report_markdown: str, max_chars: int = 6000) -> str:
    """Create a GitHub Actions summary sized for quick review."""

    if len(report_markdown) <= max_chars:
        return report_markdown
    return (
        report_markdown[: max_chars - 80].rstrip()
        + "\n\n_Report truncated. Full report is attached as an artifact._\n"
    )


def _finding_lines(index: int, item: PrioritisedFinding) -> list[str]:
    finding = item.finding
    return [
        f"### {index}. {redact_secrets(finding.title)}",
        f"**Severity:** {finding.severity.capitalize()}  ",
        f"**Location:** {_location(finding)}  ",
        f"**Why this matters:** {redact_secrets(item.reason)}  ",
        f"**Recommended action:** {_recommended_action(finding)}",
        "",
    ]


def _recommended_action(finding: Finding) -> str:
    if finding.remediation:
        return redact_secrets(truncate(finding.remediation, 240))
    if finding.documentation_url:
        return f"Review {finding.documentation_url} and update the affected resource."
    return "Review the affected resource and apply the scanner recommendation."


def _location(finding: Finding) -> str:
    if finding.file_path and finding.line_start:
        return f"{redact_secrets(finding.file_path)}:{finding.line_start}"
    if finding.file_path:
        return redact_secrets(finding.file_path)
    if finding.resource:
        return redact_secrets(finding.resource)
    return "Unknown"


def _health_trend(comparison: ComparisonSummary) -> str:
    if comparison.health_score_change is None:
        return "first scan"
    if comparison.health_score_change > 0:
        return f"up {comparison.health_score_change} points"
    if comparison.health_score_change < 0:
        return f"down {abs(comparison.health_score_change)} points"
    return "unchanged"


def _plural(count: int, label: str) -> str:
    suffix = "" if count == 1 else "s"
    return f"{count} {label}{suffix}"
