"""Markdown report generation."""

from __future__ import annotations

from .analysis_metrics import source_label
from .config import DEFAULT_PRODUCTION_PATTERNS
from .models import ComparisonSummary, Finding, ScanResult
from .prioritise import PrioritisedFinding, prioritise_findings
from .redaction import redact_secrets, truncate
from .scoring import (
    HEALTH_RISK_SCALE,
    SCORE_FORMULA_VERSION,
    SEVERITY_WEIGHTS,
    actionable_active_findings,
    actionable_findings,
)


def generate_report(
    scan: ScanResult,
    comparison: ComparisonSummary,
    *,
    top_items: list[PrioritisedFinding] | None = None,
    production_patterns: tuple[str, ...] = DEFAULT_PRODUCTION_PATTERNS,
    top_limit: int = 3,
) -> str:
    """Generate a concise Markdown report for Slack and artifacts."""

    top = top_items or prioritise_findings(
        scan.findings,
        limit=top_limit,
        production_patterns=production_patterns,
    )
    active_count = int(scan.summary.get("active_findings", len(scan.findings)))
    lines = [
        "# DriftBeacon Report",
        "",
        "## At a glance",
        f"**Repository:** {redact_secrets(scan.repository)}",
        f"**Branch:** {redact_secrets(scan.branch)}",
        f"**Commit:** `{scan.commit_sha[:12]}`",
        f"**Health score:** {_health_score_text(scan)} ({_health_trend(comparison)})",
        f"**Grade:** {_grade_text(scan)}",
        f"**Production Health:** {_production_health_score_text(scan)}",
        f"**Production Grade:** {_production_grade_text(scan)}",
        f"**Coverage:** {_coverage_text(scan)}",
        f"**Score status:** {_score_state_text(scan)}",
        f"**Active findings:** {active_count}",
        f"**Trend:** {_change_sentence(comparison)}",
        "",
        "## What happened",
        _what_happened(scan, comparison, active_count),
        "",
        "## What changed",
    ]
    lines.extend(_change_lines(comparison))
    lines.extend(["", "## Fix these first"])
    if top:
        for index, item in enumerate(top, start=1):
            lines.extend(_finding_lines(index, item, has_baseline=comparison.has_baseline))
    else:
        lines.append("No active findings were detected.")

    lines.extend(["", "## Scanner status"])
    for status in scan.scanner_statuses.values():
        pretty_state = status.status.capitalize()
        message = redact_secrets(status.message)
        suffix = f": {message}" if message else ""
        lines.append(f"- {status.name.capitalize()}: {pretty_state}{suffix}")

    if _summary_text(scan, "coverage_state", "") == "partial_coverage":
        lines.extend(["", "## Coverage warning"])
        lines.append(
            "One or more applicable scanners failed, so this score is based on partial coverage."
        )
        lines.append("Grade is provisional because one or more applicable scanners failed.")
    elif _production_grade_provisional(scan):
        lines.extend(["", "## Coverage warning"])
        lines.append("Grade is provisional because one or more applicable scanners failed.")

    lines.extend(["", "## Finding audit"])
    lines.extend(_audit_lines(scan))
    lines.extend(_breakdown_section(scan, "Finding source breakdown", "finding_source_breakdown"))
    lines.extend(
        _breakdown_section(scan, "Findings by directory group", "directory_group_breakdown")
    )
    lines.extend(_top_paths_section(scan))

    lines.extend(["", "## Scoring model"])
    lines.append(
        f"Formula {SCORE_FORMULA_VERSION}: health = round(100 * exp(-weighted_risk / "
        f"{HEALTH_RISK_SCALE})). Default weights are critical={SEVERITY_WEIGHTS['critical']}, "
        f"high={SEVERITY_WEIGHTS['high']}, medium={SEVERITY_WEIGHTS['medium']}, "
        f"low={SEVERITY_WEIGHTS['low']}. Informational findings, unknown-severity findings, "
        "passed checks, skipped scanners, scanner-error records, duplicates, and first-scan "
        "baseline status do not reduce the score."
    )
    lines.append(
        "Overall Health includes all analysed actionable findings. Production Health uses the "
        "same formula but only includes findings from paths classified as production. It does "
        "not prove deployed infrastructure is safe; path classification is heuristic and should "
        "be reviewed."
    )
    if comparison.score_formula_changed:
        lines.append(
            "The previous baseline used a different or unknown health formula, so raw health "
            "movement is not directly comparable."
        )

    if comparison.resolved_findings:
        lines.extend(["", "## Recently resolved"])
        for finding in comparison.resolved_findings[:5]:
            location = _location(finding)
            lines.append(
                f"- {_severity_label(finding)}: {redact_secrets(finding.title)} ({location})"
            )

    lines.extend(["", "_Generated by DriftBeacon._", ""])
    return "\n".join(lines)


def generate_job_summary(report_markdown: str, max_chars: int = 6000) -> str:
    """Create a GitHub Actions summary sized for quick review."""

    if len(report_markdown) <= max_chars:
        return report_markdown
    return (
        report_markdown[: max_chars - 80].rstrip()
        + "\n\n_Report truncated. Full report is attached as an artifact._\n"
    )


def _finding_lines(
    index: int, item: PrioritisedFinding, *, has_baseline: bool
) -> list[str]:
    finding = item.finding
    reason = redact_secrets(item.reason)
    if not has_baseline and reason.startswith("New "):
        reason = "Baseline " + reason.removeprefix("New ")
    return [
        f"### {index}. {redact_secrets(finding.title)}",
        f"**Severity:** {_severity_label(finding)} | **Category:** {finding.category}",
        f"**Location:** {_location(finding)}",
        f"**Why:** {reason}",
        f"**Action:** {_recommended_action(finding)}",
        "",
    ]


def _recommended_action(finding: Finding) -> str:
    if finding.remediation:
        return redact_secrets(truncate(finding.remediation, 240))
    if finding.documentation_url:
        return f"Review {finding.documentation_url} and update the affected resource."
    return "Review the affected resource and apply the scanner recommendation."


def _location(finding: Finding) -> str:
    if finding.file_path and finding.line_start:
        return f"{redact_secrets(finding.file_path)}:{finding.line_start}"
    if finding.file_path:
        return redact_secrets(finding.file_path)
    if finding.resource:
        return redact_secrets(finding.resource)
    return "Unknown"


def _audit_lines(scan: ScanResult) -> list[str]:
    summary = scan.summary
    return [
        f"- Actionable active findings: {summary.get('actionable_findings', 0)}",
        "- Ignored informational or unknown-severity findings: "
        f"{summary.get('ignored_findings', 0)}",
        f"- Passed checks: {summary.get('passed_checks', 0)}",
        f"- Duplicate findings removed: {summary.get('duplicate_findings_removed', 0)}",
        f"- Scanner errors: {summary.get('scanner_errors', 0)}",
        f"- Score reason: {_summary_text(scan, 'score_reason', 'n/a')}",
        "- Production score reason: "
        f"{_summary_text(scan, 'production_score_reason', 'n/a')}",
        "- Production actionable findings: "
        f"{summary.get('production_actionable_findings', 0)}",
        "- Score formula version: "
        f"{_summary_text(scan, 'score_formula_version', SCORE_FORMULA_VERSION)}",
    ]


def _severity_label(finding: Finding) -> str:
    if finding.severity == "unknown":
        return "Unspecified"
    return finding.severity.capitalize()


def _health_trend(comparison: ComparisonSummary) -> str:
    if comparison.score_formula_changed:
        return "health model changed"
    if comparison.health_score_change is None:
        return "first scan"
    if comparison.health_score_change > 0:
        return f"up {_plural(comparison.health_score_change, 'point')}"
    if comparison.health_score_change < 0:
        return f"down {_plural(abs(comparison.health_score_change), 'point')}"
    return "unchanged"


def _what_happened(
    scan: ScanResult, comparison: ComparisonSummary, active_count: int
) -> str:
    scanner_summary = _scanner_summary(scan)
    if active_count == 0:
        finding_summary = "No active findings were detected."
    else:
        finding_summary = f"DriftBeacon normalized {_plural(active_count, 'active finding')}."
    if comparison.has_baseline:
        return f"{scanner_summary} {finding_summary} Health is {_health_score_text(scan)}."
    return (
        f"{scanner_summary} {finding_summary} This is the first baseline, so current findings "
        "establish the starting point for future comparisons."
    )


def _scanner_summary(scan: ScanResult) -> str:
    if not scan.scanner_statuses:
        return "No scanner status was recorded."
    success = sum(1 for status in scan.scanner_statuses.values() if status.status == "success")
    partial = sum(1 for status in scan.scanner_statuses.values() if status.status == "partial")
    failed = sum(1 for status in scan.scanner_statuses.values() if status.status == "failed")
    skipped = sum(1 for status in scan.scanner_statuses.values() if status.status == "skipped")
    parts: list[str] = []
    if success:
        parts.append(_plural(success, "successful scanner"))
    if partial:
        parts.append(_plural(partial, "partial scanner"))
    if failed:
        parts.append(_plural(failed, "failed scanner"))
    if skipped:
        parts.append(_plural(skipped, "skipped scanner"))
    return "Scanner status: " + ", ".join(parts) + "."


def _change_lines(comparison: ComparisonSummary) -> list[str]:
    if not comparison.has_baseline:
        return ["- First scan: no previous baseline existed."]
    new_count = len(actionable_active_findings(comparison.new_findings))
    recurring_count = len(actionable_active_findings(comparison.recurring_findings))
    resolved_count = len(actionable_findings(comparison.resolved_findings))
    return [
        f"- {_plural(new_count, 'new finding')}",
        f"- {_plural(recurring_count, 'recurring finding')}",
        f"- {_plural(resolved_count, 'resolved finding')}",
        f"- {_plural(len(comparison.severity_changes), 'severity change')}",
        "- Health model changed; score movement is not directly comparable."
        if comparison.score_formula_changed
        else f"- Health score {_health_trend(comparison)}",
    ]


def _change_sentence(comparison: ComparisonSummary) -> str:
    if not comparison.has_baseline:
        return "first scan"
    new_count = len(actionable_active_findings(comparison.new_findings))
    recurring_count = len(actionable_active_findings(comparison.recurring_findings))
    resolved_count = len(actionable_findings(comparison.resolved_findings))
    return (
        f"{_plural(new_count, 'new finding')}, "
        f"{_plural(recurring_count, 'recurring finding')}, "
        f"{_plural(resolved_count, 'resolved finding')}, "
        + (
            "health model changed"
            if comparison.score_formula_changed
            else f"health score {_health_trend(comparison)}"
        )
    )


def _health_score_text(scan: ScanResult) -> str:
    if scan.health_score is None:
        return "Not scored"
    return f"{scan.health_score}/100"


def _production_health_score_text(scan: ScanResult) -> str:
    score = _summary_optional_int(scan, "production_health_score")
    if score is None:
        return "Not scored"
    return f"{score}/100"


def _grade_text(scan: ScanResult) -> str:
    return _display_grade(_grade_for_score(scan.health_score), _grade_provisional(scan))


def _production_grade_text(scan: ScanResult) -> str:
    grade = _summary_text(
        scan,
        "production_grade",
        _grade_for_score(_summary_optional_int(scan, "production_health_score")),
    )
    return _display_grade(grade, _production_grade_provisional(scan))


def _grade_for_score(score: int | None) -> str:
    if score is None:
        return "N/A"
    if score >= 90:
        return "A"
    if score >= 80:
        return "B"
    if score >= 70:
        return "C"
    if score >= 60:
        return "D"
    return "F"


def _display_grade(grade: str, provisional: bool) -> str:
    return f"{grade}*" if provisional and grade != "N/A" else grade


def _grade_provisional(scan: ScanResult) -> bool:
    return _summary_bool(scan, "grade_provisional") or (
        scan.health_score is not None
        and _summary_text(scan, "coverage_state", "") == "partial_coverage"
    )


def _production_grade_provisional(scan: ScanResult) -> bool:
    return _summary_bool(scan, "production_grade_provisional")


def _summary_text(scan: ScanResult, key: str, default: str) -> str:
    value = scan.summary.get(key, default)
    return str(value)


def _summary_optional_int(scan: ScanResult, key: str) -> int | None:
    value = scan.summary.get(key)
    return value if isinstance(value, int) else None


def _summary_bool(scan: ScanResult, key: str) -> bool:
    return scan.summary.get(key) is True


def _coverage_text(scan: ScanResult) -> str:
    labels = {
        "complete_coverage": "Complete",
        "partial_coverage": "Partial",
        "not_scored_no_supported_files": "Not scored",
        "not_scored_all_scanners_failed": "Not scored",
    }
    return labels.get(_summary_text(scan, "coverage_state", "unknown"), "Unknown")


def _score_state_text(scan: ScanResult) -> str:
    labels = {
        "scored": "Scored",
        "not_scored_no_supported_files": "Not scored",
        "not_scored_all_scanners_failed": "Not scored",
    }
    return labels.get(_summary_text(scan, "score_state", "unknown"), "Unknown")


def _breakdown_label(heading: str) -> str:
    return "Directory group" if "directory" in heading.lower() else "Source"


def _breakdown_section(scan: ScanResult, heading: str, key: str) -> list[str]:
    raw = scan.summary.get(key)
    if not isinstance(raw, dict):
        return []
    lines = [
        "",
        f"## {heading}",
        "",
        f"| {_breakdown_label(heading)} | Critical | High | Medium | Low | Total |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    if not raw:
        lines.append("| - | 0 | 0 | 0 | 0 | 0 |")
        return lines
    for source, row in sorted(
        raw.items(),
        key=lambda item: item[1].get("total_actionable", 0)
        if isinstance(item[1], dict)
        else 0,
        reverse=True,
    ):
        if not isinstance(row, dict):
            continue
        lines.append(
            "| "
            f"{source_label(str(source))} | {row.get('critical', 0)} | {row.get('high', 0)} | "
            f"{row.get('medium', 0)} | {row.get('low', 0)} | "
            f"{row.get('total_actionable', 0)} |"
        )
    return lines


def _top_paths_section(scan: ScanResult) -> list[str]:
    lines: list[str] = []
    lines.extend(
        _top_path_table(
            scan.summary.get("top_directories"),
            heading="Top directories by actionable findings",
            label="Directory",
        )
    )
    lines.extend(
        _top_path_table(
            scan.summary.get("top_files"),
            heading="Top files by actionable findings",
            label="File",
        )
    )
    return lines


def _top_path_table(raw: object, *, heading: str, label: str) -> list[str]:
    if not isinstance(raw, list) or not raw:
        return []
    lines = [
        "",
        f"## {heading}",
        "",
        f"| {label} | Actionable findings |",
        "| --- | ---: |",
    ]
    for item in raw[:10]:
        if isinstance(item, dict):
            lines.append(
                f"| {item.get('path', 'unknown')} | "
                f"{item.get('actionable_findings', 0)} |"
            )
    return lines


def _plural(count: int, label: str) -> str:
    suffix = "" if count == 1 else "s"
    return f"{count} {label}{suffix}"
